# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(645, 522)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("main.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        about.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(about)
        self.label.setGeometry(QtCore.QRect(130, 20, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(about)
        self.textBrowser.setGeometry(QtCore.QRect(20, 90, 611, 401))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "Wind Power Calculator"))
        self.label.setText(_translate("about", "About the program"))
        self.textBrowser.setHtml(_translate("about", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><a name=\"docs-internal-guid-e9a60602-7fff-96a7-b163-30e3335c7ef6\"></a><span style=\" font-family:\'Arial\'; font-size:11pt; color:#d3d3d3; background-color:transparent;\">W</span><span style=\" font-family:\'Arial\'; font-size:11pt; color:#d3d3d3; background-color:transparent;\">ind Power Calculator is the desktop application that allows you to calculate the wind generated power in a particular region of Kazakhstan. The calculations are based on such parameters as wind speed, radius of blades and air density. The wind speed in every region is parsing from the internet in real time. It is achieved with Python OpenWeatherMap api. It is a free web library with the access to weather parameters of any city.  </span><span style=\" font-size:8pt; color:#d3d3d3;\"><br /></span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#d3d3d3; background-color:transparent;\">The program is implemented in python with a use of PyQt, the cross-platform GUI toolkit. </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; font-family:\'Arial\'; font-size:11pt; color:#d3d3d3;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:\'Arial\'; font-size:11pt; color:#d3d3d3; background-color:transparent;\">All source file are provided by the link: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-size:10pt; text-decoration: underline; color:#00aaff;\">https://github.com/madiyarsh/wind-app</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; font-size:10pt; color:#0000ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:\'Arial\'; font-size:9pt; color:#d3d3d3; background-color:transparent;\">Developed for </span><span style=\" font-family:\'Arial\'; font-size:9pt; font-style:italic; color:#d3d3d3; background-color:transparent;\">MECE 700 &quot;</span><span style=\" font-size:9pt; font-style:italic; color:#d3d3d3;\">Industrial and Commercial Energy Systems</span><span style=\" font-family:\'Arial\'; font-size:9pt; font-style:italic; color:#d3d3d3; background-color:transparent;\">&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:\'Arial\'; font-size:9pt; color:#d3d3d3; background-color:transparent;\">Developed by </span><span style=\" font-family:\'Arial\'; font-size:9pt; font-weight:600; color:#d3d3d3; background-color:transparent;\">Madiyar Sharipov</span><span style=\" font-family:\'Arial\'; font-size:9pt; color:#d3d3d3; background-color:transparent;\"> (madiyar.sharipov@nu.edu.kz)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:\'Arial\'; font-size:9pt; color:#d3d3d3; background-color:transparent;\">       </span><span style=\" font-family:\'Arial\'; font-size:9pt; font-weight:600; color:#d3d3d3; background-color:transparent;\">Meruyert Zhuvandykova</span><span style=\" font-family:\'Arial\'; font-size:9pt; color:#d3d3d3; background-color:transparent;\"> (meruyert.zhuvandykova@nu.edu.kz)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#d3d3d3;\"><br /></span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    about = QtWidgets.QWidget()
    ui = Ui_about()
    ui.setupUi(about)
    about.show()
    sys.exit(app.exec_())
