# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import sys
import pyowm
import openpyxl
from PyQt5.QtWidgets import QMessageBox, QWidget, QToolTip, QPushButton, QApplication, QLabel
from PyQt5.QtGui import QFont, QMovie
from forall import Ui_Form
from about import Ui_about
from datetime import date, datetime

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 578)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("main.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 120, 371, 41))
        self.comboBox.setObjectName("comboBox")
        self.areaLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.areaLabel.setGeometry(QtCore.QRect(170, 190, 371, 41))
        self.areaLabel.setAcceptDrops(True)
        self.areaLabel.setAutoFillBackground(False)
        self.areaLabel.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.areaLabel.setInputMask("")
        self.areaLabel.setReadOnly(True)
        self.areaLabel.setPlaceholderText("")
        self.areaLabel.setClearButtonEnabled(True)
        self.areaLabel.setObjectName("areaLabel")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 330, 371, 41))
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 470, 181, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 190, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(550, 260, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 260, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.areaLabel_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.areaLabel_2.setGeometry(QtCore.QRect(170, 260, 371, 41))
        self.areaLabel_2.setAcceptDrops(True)
        self.areaLabel_2.setAutoFillBackground(False)
        self.areaLabel_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.areaLabel_2.setInputMask("")
        self.areaLabel_2.setText("")
        self.areaLabel_2.setPlaceholderText("")
        self.areaLabel_2.setClearButtonEnabled(True)
        self.areaLabel_2.setObjectName("areaLabel_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 20, 41, 41))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 70, 41, 41))
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 400, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 400, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.areaLabel_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.areaLabel_3.setGeometry(QtCore.QRect(170, 400, 371, 41))
        self.areaLabel_3.setAcceptDrops(True)
        self.areaLabel_3.setAutoFillBackground(False)
        self.areaLabel_3.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.areaLabel_3.setInputMask("")
        self.areaLabel_3.setText("")
        self.areaLabel_3.setPlaceholderText("")
        self.areaLabel_3.setClearButtonEnabled(True)
        self.areaLabel_3.setObjectName("areaLabel_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOne_Region = QtWidgets.QAction(MainWindow)
        self.actionOne_Region.setObjectName("actionOne_Region")
        self.actionAll_Regions = QtWidgets.QAction(MainWindow)
        self.actionAll_Regions.setObjectName("actionAll_Regions")
        self.actionLast_update = QtWidgets.QAction(MainWindow)
        self.actionLast_update.setObjectName("actionLast_update")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wind Power Calculator"))
        self.label.setText(_translate("MainWindow", "Power Calculation"))
        self.label_2.setText(_translate("MainWindow", "Region"))
        self.label_3.setText(_translate("MainWindow", "Speed"))
        self.label_4.setText(_translate("MainWindow", "Air density"))
        self.areaLabel.setText(_translate("MainWindow", "No need to fill: data taken online"))
        self.lineEdit_2.setText(_translate("MainWindow", "1.24"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.label_5.setText(_translate("MainWindow", "m/s"))
        self.label_6.setText(_translate("MainWindow", "kg/m3"))
        self.label_7.setText(_translate("MainWindow", "m2"))
        self.label_8.setText(_translate("MainWindow", "Area"))
        self.label_9.setText(_translate("MainWindow", "%"))
        self.label_10.setText(_translate("MainWindow", "Efficiency"))
        self.actionOne_Region.setText(_translate("MainWindow", "One Region"))
        self.actionAll_Regions.setText(_translate("MainWindow", "All Regions"))
        self.actionLast_update.setText(_translate("MainWindow", "Last update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
